### ISSUE TITLE
Monkey business

### ISSUE THREAD

**Issue by xl0** [xl0/lovely-numpy#2]
@ido-nuc , we have a UX issue with monkey_patch. Once patched, you lose easy access to the values of the array, and we have no way of adding `arr.v` like in lovely-tensors.

I think we have one last option:
```py
import lovely_numpy as np

...
...
```
And do the magic this way. Inside `lovely_numpy` `from numpy import *`  and wrapp np.ndarray (and np.generic for good measure) in a thin class that would allow all the __repr__ and .rgb goodies.

What do you think?

**Comment by idow09** [comment]
I'm not sure I understand the problem with the current implementation. I mean, we knew in the first place that we can't patch those attributes since we are dealing with a C object. Or you had hope that the `set_string_function` solution is applicable as a generic solution to all of our needs?

Anyways, I'm not sure that I fully understand the full implications of your suggestion either, but it sounds reasonable to me that this is the way to go given the limitations on the C object. I'm still afraid though that it will make the library a no-go for people relying heavily on `numpy`. Personally I would be much more cautious if I needed to interact with a 3rd party for all of my numpy code, only to get the lovely-numpy functionality.

I'll discuss this with some friends and see if we come up with an alternative but I currently see no other option (other than using the function in their regular form of course). Also I'm pretty busy at work right now so I'll try to get to it ASAP but of course you don't have to wait for me.

**Comment by xl0** [comment]
Yep, but I did not realize how much of a pain it would be to have an ndarray with `__repr__` that can not show values until I tried using it in my code. Had to revert to calling lovely() directly right away.

I think it's ok if some people are hesitant. People are hesitant to use lovely-tensors monkey_patch too. Of course, the function call behaviour will be preserved in any case, you should always be able to do
```py
from lovely_numpy import lovely, rgb, plt

lovely(a)
rgb(b)
plt(c)
```

or even
```py
import lovely_numpy as lnp

lnp.lovely(a)
lnp.rgb(b)
lnp.cnahs(c)
```

It's still a huge quality of life improvement over having to visualize and summarize the data manually every time.

But if it's possible, I'd like to have the OOP functionality. And make sure it's actually usable and the experience is smooth.

Let me take on this one. Do you want to take on .plt? plt is relatively isolated, and other parts of lovely-numpy don't rely on it, so it's much less time-sensitive.

I will then start moving parts of -tensors and -jax over to use the generic -numpy functionality where it makes sense.

**Comment by xl0** [comment]
Yep, but I did not realize how much of a pain it would be to have an ndarray with `__repr__` that can not show values until I tried using it in my code. Had to revert to calling lovely() directly right away.

I think it's ok if some people are hesitant. People are hesitant to use lovely-tensors monkey_patch too. Of course, the function call behaviour will be preserved in any case, you should always be able to do
```py
from lovely_numpy import lovely, rgb, plt

lovely(a)
rgb(b)
plt(c)
```

or even
```py
import lovely_numpy as lnp

lnp.lovely(a)
lnp.rgb(b)
lnp.cnahs(c)
```

It's still a huge quality of life improvement over having to visualize and summarize the data manually every time.

But if it's possible, I'd like to have the OOP functionality. And make sure it's actually usable and the experience is smooth.

Let me take on this one. Do you want to take on .plt? plt is relatively isolated, and other parts of lovely-numpy don't rely on it, so it's much less time-sensitive.

I will then start moving parts of -tensors and -jax over to use the generic -numpy functionality where it makes sense.

**Comment by idow09** [comment]
I see. Now it's much clearer to me. So you take the major OOP refactor, I'll try to take care of `.plt`. I hope I can get to it soon...

**Comment by idow09** [comment]
Feel free to assign me as well
