### ISSUE TITLE
Port `plot()` from Lovely Tensors

### ISSUE THREAD

**Issue by xl0** [xl0/lovely-numpy#4]
I think it should be a generic `plot_np(x: nd.array, ... )` that is wrapped by a thin library-specific wrapper.
Please note, at the moment the summary string is calculated inside `_plt()`:

```py
    orig_str = str(lovely(t, color=False))
```

This code should be moved outside the generic function (`plot_np` should accept the summary) because the summary is backend-specific: it contains things like `grad` and `cuda` for torch.

@ido-nuc , would you like to take this one?

**Comment by idow09** [comment]
Sure!

You want the code generic because you want it somehow shared between the packages, or simply for making it cleaner?
Because in [lovely-tensors's `_plot`](https://github.com/xl0/lovely-tensors/blob/master/lovely_tensors/repr_plt.py) there is more backend specific code other than the summary (e.g. `.cuda`, `.detach`, etc.)

**Comment by xl0** [comment]
Yes, I want to share what can be shared (-tensors and -jax will import -numpy).

**Comment by xl0** [comment]
@idow09 , I reworked the library quite a bit and released 0.2.0, please have a look. 

Unfortunately monkey-patching had to go, but I feel the new method is cleaner and more consistent.

**Comment by idow09** [comment]
Sure, I'll look into it! Thanks for the notification.

**Comment by xl0** [comment]
Done.
